
--Print class routine for teacher--

SELECT D.DAY, CL.CLASS_TIME, C.CLASS_NAME, S.SECTION_NAME, SUB.SUBJECT_NAME, 
CR.ROOM_NUMBER, E.FIRST_NAME||' '||E.LAST_NAME||' ('||E.EMPLOYEE_ID||')' EMPLOYEE_NAME
FROM CLASS C, SECTIONS S, ROUTINE_MASTER RM, ROUTINE_DETAIL RD, DAY_OF_WEEK D, CLASSROOMS CR, 
CLASS_SLOT CL, SUBJECTS SUB, EMPLOYEES E
WHERE C.CLASS_ID = RM.CLASS_ID
AND S.SECTION_ID = RM.SECTION_ID
AND RM.ROUTINE_M_ID = RD.ROUTINE_M_ID
AND RM.DAY_ID = D.DAY_ID
AND CR.CLASSROOM_ID = RM.CLASSROOM_ID
AND CL.SLOT_ID = RD.SLOT_ID
AND SUB.SUBJECT_ID = RD.SUBJECT_ID
AND E.EMPLOYEE_ID = RD.TEACHER_ID
AND E.EMPLOYEE_ID = :P27_EMPLOYEE_ID
ORDER BY RM.DAY_ID, CL.SLOT_ID
