
SELECT E.EMPLOYEE_ID, E.FIRST_NAME||' '||E.LAST_NAME EMPLOYEE_NAME, ED.STATUS, ED.DESCRIPTION, EM.AT_DATE
FROM EMPLOYEES E, EMP_AT_D ED, EMP_AT_M EM
WHERE E.EMPLOYEE_ID = ED.EMPLOYEE_ID
AND ED.AT_M_ID = EM.AT_M_ID
AND TRUNC(EM.AT_DATE) = TO_DATE(:P217_AT_DATE, 'DD-MON-RR')
