
--Print a specific student marksheet--

SELECT S.FIRST_NAME||' '||S.LAST_NAME||' -'||S.STUDENT_ID Student_name, C.CLASS_NAME, SEC.SECTION_NAME,
EM.EXAM_NAME, SUB.SUBJECT_NAME, MD.MARKS, MD.GRADE, MD.GRADE_POINT, MD.STATUS
FROM STUDENTS S, CLASS C, ADMISSION A, SECTIONS SEC, EXAMS_M EM, MARKS_LIST_M MM , MARKS_LIST_D MD, SUBJECTS SUB
WHERE A.CLASS_ID = C.CLASS_ID
AND A.STUDENT_ID = S.STUDENT_ID
AND A.SECTION_ID = SEC.SECTION_ID
AND EM.EXAM_M_ID = MM.EXAM_M_ID
AND MM.MARKS_LIST_M_ID = MD.MARKS_LIST_M_ID
AND MD.STUDENT_ID = S.STUDENT_ID
AND SUB.SUBJECT_ID = MM.SUBJECT_ID
AND S.STUDENT_ID = :P128_STUDENT_ID
ORDER BY EM.EXAM_M_ID, SUB.SUBJECT_ID