
--Class and section wise subject--

SELECT CS.ID, C.CLASS_NAME, S.SECTION_NAME, SUB.SUBJECT_NAME, R.ROOM_NUMBER
FROM CLASS_SUBJECTS CS, CLASS C, SECTIONS S, SUBJECTS SUB, CLASSROOMS R
WHERE C.CLASS_ID = CS.CLASS_ID
AND S.SECTION_ID = CS.SECTION_ID
AND SUB.SUBJECT_ID = CS.SUBJECT_ID
AND R.CLASSROOM_ID = CS.CLASSROOM_ID
--ORDER BY C.CLASS_ID, S.SECTION_ID, SUB.SUBJECT_ID