
--Subject wise marks and color--

SELECT MD.MARKS_LIST_D_ID, S.STUDENT_ID, S.FIRST_NAME||' '||S.LAST_NAME Student_name, 
MD.MARKS, MD.GRADE, MD.GRADE_POINT, MD.STATUS,
    CASE
        WHEN MD.STATUS = 'Pass' THEN 'success'
        WHEN MD.STATUS = 'Fail' THEN 'warning'
    END AS Status_colour
FROM MARKS_LIST_D MD, STUDENTS S, MARKS_LIST_M MM
WHERE MD.STUDENT_ID = S.STUDENT_ID
AND MM.MARKS_LIST_M_ID = MD.MARKS_LIST_M_ID
AND MM.CLASS_ID = NVL(:P211_CLASS_ID, MM.CLASS_ID)
AND MM.SECTION_ID = NVL(:P211_SECTION_ID, MM.SECTION_ID)
AND MM.SUBJECT_ID = NVL(:P211_SUBJECT_ID, MM.SUBJECT_ID)
AND MM.EXAM_M_ID = NVL(:P211_EXAM_M_ID, MM.EXAM_M_ID)