
SELECT S.FIRST_NAME||' '||S.LAST_NAME STUDENT_NAME, SP.PAYMENT_DATE, E.FIRST_NAME||' '||E.LAST_NAME USER_NAME,
SP.PREVIOUS_DUE, SP.REMAINING_DUE, SP.PAID
FROM STU_PAYMENT SP, STUDENTS S, COLLECTION_M CM, EMPLOYEES E, EMP_USERS EU
WHERE CM.STUDENT_ID = S.STUDENT_ID
AND CM.COLLECTION_M_ID = SP.COLLECTION_M_ID
AND E.EMPLOYEE_ID = EU.EMPLOYEE_ID
AND EU.USER_ID = SP.USER_ID


--Login user--

SELECT E.FIRST_NAME||' '||E.LAST_NAME Display, U.USER_ID
FROM EMPLOYEES E, EMP_USERS U
WHERE E.EMPLOYEE_ID = U.EMPLOYEE_ID
AND UPPER(USER_NAME) = UPPER(:APP_USER)