
SELECT ROWNUM, W.W_ID, S.STUDENT_ID, S.FIRST_NAME||' '||S.LAST_NAME STUDENT_NAME, W.WAIVER, A.YEAR_NAME 
FROM STUDENTS S, WAIVER W, ACADEMIC_YEARS A
WHERE S.STUDENT_ID = W.STUDENT_ID 
AND A.ACADEMIC_YEAR_ID = W.ACADEMIC_YEAR_ID